name: Build Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/telegramdesktop/tdesktop/centos_env:latest

      - name: Build inside Docker
        run: |
          docker run --rm \
            -u $(id -u) \
            -v "$PWD:/usr/src/tdesktop" \
            -w /usr/src/tdesktop \
            -e NINJAFLAGS="-j1 -l1" \
            ghcr.io/telegramdesktop/tdesktop/centos_env:latest \
            bash -c "
              /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
                -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_DISABLE_FIND_PACKAGE_GObjectIntrospection=ON \
                -DCMAKE_JOB_POOLS=link=1 \
                -DBUILD_SHARED_LIBS=ON \
                -DCMAKE_CXX_FLAGS='-O2 -g0 -fno-fat-lto-objects' \
                -DTDESKTOP_API_ID=2040 \
                -DTDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627
            "

      - name: Debug files
        run: |
          ls -R out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AyuGram-Linux
          path: out/Release
